### ISSUE TITLE
initial error 

### ISSUE THREAD

**Issue by atuljain** [seanauriti/coderbounty#88]
while i reclone this project and trying to run , i am geting error 

CommandError: System check identified some issues:

ERRORS:
<class 'website.admin.IssueAdmin'>: (admin.E108) The value of 'list_display[11]' refers to 'solution', which is not a callable, an attribute of 'IssueAdmin', or an attribute or method on 'website.Issue'.

**Comment by seanauriti** [comment]
Did you run the migrations?

**Comment by atuljain** [comment]
yes

**Comment by seanauriti** [comment]
Reverted, should work now

**Comment by atuljain** [comment]
still facing same problem

**Comment by seanauriti** [comment]
You pulled the latest master?

**Comment by atuljain** [comment]
yes

**Comment by atuljain** [comment]
I just reinstalled Django=1.8.6 as described in requirement file but it seems again problem with version 

https://groups.google.com/forum/#!topic/django-oscar/1c-b62VMZdw
https://github.com/django-extensions/django-extensions/issues/761

**Comment by seanauriti** [comment]
Working fine for me

**Comment by atuljain** [comment]
just take a look i am trying to solve it 


Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 63, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'actstream' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.

**Comment by atuljain** [comment]
it's working with django=1.8.5

**Comment by seanauriti** [comment]
Excellent
